FROM node AS builder
WORKDIR /app
ENV MODE=production

COPY package.json package.json
COPY yarn.lock yarn.lock

RUN yarn install -s --frozen-lockfile --production

COPY . .

RUN yarn build

FROM httpd as production
WORKDIR /usr/local/apache2/htdocs/
EXPOSE 80

RUN rm -rf *

COPY --from=builder /app/dist .

ENTRYPOINT ["httpd-foreground"]
